apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloudant
spec:
  hosts:
  - '*.appdomain.cloud'
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloudant
spec:
  hosts:
  - '*.appdomain.cloud'
  tls:
  - match:
    - port: 443
      sni_hosts:
      - '*.appdomain.cloud'
    route:
    - destination:
        host: '*.appdomain.cloud'
        port:
          number: 443
      weight: 100