kind: Service
apiVersion: v1
metadata:
  name: authors
  labels:
    app: authors
spec:
  selector:
    app: authors
  ports:
    - port: 3000
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: authors
spec:
  replicas: 1
  template:
    metadata:
      annotations: 
        sidecar.istio.io/inject: "true"      
      labels:
        app: authors
        version: v1
    spec:
      containers:
      - name: authors
        image: authors:1
#        args: ["--spring.profiles.active=deployed"]
        ports:
        - containerPort: 3000
#        livenessProbe:
#          exec:
#            command: ["sh", "-c", "curl -s http://localhost:3000/"]
#          initialDelaySeconds: 35
#        readinessProbe:
#          exec:
#            command: ["sh", "-c", "curl -s http://localhost:3000/health | grep -q UP"]
#          initialDelaySeconds: 40
      restartPolicy: Always
---
