apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "protect-web-api"
spec:
  targets:
  - name: web-api
  origins:
  - jwt:
      issuer: "appid-oauth.ng.bluemix.net"
      jwksUri: "https://appid-oauth.ng.bluemix.net/oauth/v3/892d676a-4e9d-48c9-82bd-1d49091d232f/publickeys"
  principalBinding: USE_ORIGIN